remove print statements
I need to fix this error first 

/builds/moonsun/moonsun.gitlab.io/java/src/main/java/hello/HelloWorld.java:12: 
error: illegal start of expression
    int[] result = twoSum.twoSum({2,7,11,15}, 9);